@startuml
scale 2
title "UML Class Diagram"
class Point {
	-__nums: Nums
	-__case: case
	+setNums(): None
	+setCase(): None
	+getNums(): Nums
	+getCase(): int
	+getMin(): int
	+getMax(): int
	+printStats: None
}
@enduml