@startuml
scale 2
title "UML Class Diagram"
class Polygon {
	-__numPoints: int
	-__points: List[int]
	+area(): float
	+setPoints(): None
	+getPoints(): List[Point]
	+setNumPoints(): None
	+getNumPoints(): int
}
@enduml